### ISSUE TITLE
WSProxy inside Multi action 

### ISSUE THREAD

**Issue by kjetilpp** [ybizeul/StreamDeckWS#2]
Hello. Have some WSProxy actions inside an multi action, they are not working. 
Think the issue is that the websocket is not created, Node-red says it's disconnected. 

If i put a WSProxy action with same nedpoint next to the multi action, then the multi action is working, and node-red says it's connected.

SD Software: 4.9.0.13177
WSProxy: 1.1.7

**Comment by ybizeul** [comment]
Thanks for your report.

Indeed, as the websocket is opened when the key is actually displayed, in the context of a multi action it'll try to trigger while the socket has never been opened. I'll look into this.

**Comment by ybizeul** [comment]
Fixed in 1.1.8
