### ISSUE TITLE
SetImage only works if no default image is defined

### ISSUE THREAD

**Issue by jwillmer** [ybizeul/StreamDeckWS#21]
I don't know if this is a limitation of StreamDeck or the plugin but if I set a default image in StreamDeck then this plugin is not able to override it. If I klick on "Reset to default" the image set by the plugin is showing up.

**Comment by ybizeul** [comment]
Sorry for missing this bug.
Yes I think it's a "feature" of StreamDeck, same goes with the Title actually if I remember correctly. Feel free to comment/reopen if you still think there is a bug
