### ISSUE TITLE
Support websocket connection with TLS  (self signed certificate)

### ISSUE THREAD

**Issue by e-skulk** [ybizeul/StreamDeckWS#22]
Hi, my Node-RED server uses a self signed certificate for websocket connections over TLS. The server is accessible with a web browser over https. I am using a WSProxy Multistate at stream deck with the following WebSocket url:
wss://<my_nodered_ip>:<my_nodered_port>/streamdeck

The websocket connection without TLS is working fine: data can be exchanged between WSProxy and Node-RED server.
The websocket connection with TLS receives no data at Node-RED (checked by a debug node directly after websocket input). 
A wireshark trace shows that the TLS connection is started and data is transmitted encrypted to Node-RED.

Do you support websocket connections over TLS with a self signed certifcate? In future version?

**Comment by ybizeul** [comment]
What if you go with Safari to `wss://<my_nodered_ip>:<my_nodered_port>/` and accept the certificate once ?

**Comment by e-skulk** [comment]
The Node-RED site opens (certificate is already accepted in Safari)

**Comment by ybizeul** [comment]
I did some quick work with this version, I'm not sure if this is actually possible, but give it a shot and tell me how it goes.
Enable Insecure SSL, then you might have to restart StreamDeck (or change the URL and change it back to force a reconnect)
[org.tynsoe.streamdeck.wsproxy.streamDeckPlugin.zip](https://github.com/ybizeul/StreamDeckWS/files/6954583/org.tynsoe.streamdeck.wsproxy.streamDeckPlugin.zip)

**Comment by e-skulk** [comment]
It seems that the TLS handshake is not successfully finished. A change cipher spec command (from TLSv1.3 to TLSv1.2) is sent to Node-RED. Than Node-RED seems to accept the change and closes the TCP connection with FIN, ACK. The communication restarts but still with TLS v1.3 and same behaviour. Please see trace below. My test setup is as follows:
- StreamDeck with one button of type WSProxy Multistate
- WebSocket: wss://192.168.0.83:<my_nodered_port>/streamdeck
- insecure SSL: true
- id: test
- Node-RED v1.3.6 with self signed certificate (SHA256 / RSA 2048bit / valid until Juli 2022)
- no proxy in between

Trace without pressing the StreamDeck button is at [pcap-file](https://www.file-upload.net/download-14658376/WsProxyTest.pcap.html).
Pressing the button doesn't seem to trigger a websocket request (maybe because handshake is not completed?)

Node-RED log shows nothing special. Maybe the issue is with Node-RED? Or does StreamDeck not allow to switch to TLSv1.2? Anything else?

**Comment by e-skulk** [comment]
I think its a Node-RED misconfiguration on my side or some issue in their code, because I found some won't fixes in its issue tracker regarding this topic. Lately I experimented with:
a) NODE_TLS_REJECT_UNAUTHORIZED=0
b) allow any client over websocket with _webSocketNodeVerifyClient_ in settings.js
But encryption over TLS is still not working. 

You may close the ticket. Thank you for trying to enable insecure SSL.

**Comment by ybizeul** [comment]
Thanks for the update.
From your comment I'm guessing, you implemented TLS directly in node red, not in a proxy ?

I think I shouldn't commit the change you a I'm not even sure it's changing anything

**Comment by e-skulk** [comment]
Yes, I implemented TLS in Node-RED. I would not commit it.

**Comment by ybizeul** [comment]
Thanks !
