### ISSUE TITLE
Possibility to create a specific function for willAppear and setImage

### ISSUE THREAD

**Issue by DhSufi** [ybizeul/StreamDeckWS#29]
First of all thank you so much for your work.

I was checking the code and found this:

> // The connection to this server already exists
> 
> // When starting up, all the keys are rapidly sent but the connection is
> // not available when keys after the very first one are added, so we
> // simply wait a bit and retry the send message

As long as I understand, the first instance of the plugin creates a websocket client and sends its message. Then the other plugin instances wait for that client to be avilable an then all plugin instances use that websocket client to send the messages.
Will be possible to create a start up funcion that makes each plugin instante use its own websocket client so all the the setImage events can load fast on start up. Then close all those clients and perform the current procedure of making all plugin instances to use the same websocket client?

Thanks for your time and consideration
Best regards.

https://user-images.githubusercontent.com/75437459/220183549-fe9beff3-3453-4d02-bd6a-fbbef1222742.mp4

**Comment by ybizeul** [comment]
Thanks @DhSufi.

I think I understand the overall request, but I'm still confused on how it'll make things faster. Let's say a websocket takes 1s to establish, after that everything should be fast, but if we instantiate 5 websockets at once, it'll still be 1s to establish for each, so how will that be faster, compared to stacking all the request and send it at once once the socket is available ?

**Comment by DhSufi** [comment]
You are absolutely right. So let me ask from my ignorance. Is possible to change this part of the code to the following one so things can be speed up a little bit? 
 
Change the "if" to a "while loop".

Current code:

```
if (connections[remoteServer].websocket.readyState == 0) {
			setTimeout(() => {
				connections[remoteServer].websocket.send(JSON.stringify(message))
			},1000)
		}
		else {
			connections[remoteServer].websocket.send(JSON.stringify(message))
		}
```

Is this possible?:

```
while (true) { 
    if (connections[remoteServer].websocket.readyState == 1) {  
      connections[remoteServer].websocket.send(JSON.stringify(message))
    }
}
```

Again thank you so much for your work and time. I am learning a lot reading your code.
