### ISSUE TITLE
How to use the sd-input and sd-output nodes?

### ISSUE THREAD

**Issue by oskapt** [ybizeul/StreamDeckWS#6]
HI! Great plugin. I'm setting it up to have better logical control of mimoLive from the Stream Deck. I currently use HTTP calls through Keyboard Maestro, but I want better logic for identifying which layers are active, or which sub-components of a layer are active. I can do this in Node-RED, but until discovering your plugin, I hadn't found a good way to get data back and forth between the Stream Deck and Node-RED.

Your docs cover the basic workflow, but I saw there's also sd-input/output nodes. sd-input seems to work, but sd-output says, "message has no streamdeckID." I don't see a place to set that in the Stream Deck software (macOS), nor anywhere else, for that matter. If I set it to the name of the Stream Deck in its software, the output tells me that there's no context for that name.

Where is this set?

**Comment by oskapt** [comment]
Of course, true to form, I figured out where it's being set. I thought it was the ID of the Stream Deck itself, but I see now that it's the ID of the button, and it's coming out of the sd-input node. I'll have to hunt down where it's getting dropped. Disregard!

**Comment by ybizeul** [comment]
It should be better documented, these nodes were added after the fact to try and help with the result returned to the Stream Deck (Really it's mostly about `context` value, but an initial even has to be received at some point. I'll leave that open and mark as doc
