### ISSUE TITLE
stream deck screen saver

### ISSUE THREAD

**Issue by stk21** [ybizeul/StreamDeckWS#8]
Yann.  I think I may have found a bug.  I have a single button set to play/pause my office sonos.  I notice that is the deck goes into screen saver mode, when it comes out of screen saver, it will fire the button.

I have also experienced this if you try and change the background of the screen saver in the settings page, it will fire the button when you save or cancel.

Let me know if you can reproduce.

Doug

**Comment by ybizeul** [comment]
I think you’re not filtering the event on the web service side. This plugin will send all kind of events (like willAppear, willDisappear, etc https://developer.elgato.com/documentation/stream-deck/sdk/events-received/).

you want to make sure that on the web service side you act only ok « keyDown » event for example. The event type is part of the message you get as a json string

**Comment by stk21** [comment]
Thank you sir.  I dug into this last night and was seeing my error.  No bug.  bad implementation on my part. 

Thanks
